### ISSUE TITLE
The mysterious space character behind gitmoji

### ISSUE THREAD

**Issue by gbaian10** [ljnsn/cz-conventional-gitmoji#242]
![image](https://github.com/user-attachments/assets/3aa76f6e-49e4-4e70-9fc7-31de45c78be4)
![image](https://github.com/user-attachments/assets/2dd6e95b-4eb2-458d-ab93-2eb598134bed)

Is there any special meaning to the mysterious space symbol behind the gitmoji ?
These extra spaces can affect the regular expression checks.

In my case, I merged and squashed messages on GitHub and manually added these gitmojis.
However, for specific symbols like `refactor`, an extra space is needed to match.

After I submitted this squash merge, I found that the `cz ch` command couldn't detect it because it was missing a space.

---

![image](https://github.com/user-attachments/assets/ea1490f1-4459-4ae6-b115-d88a89bf9e71)

Also, when it outputs the changelog, the extra spaces don't look very nice.

**Comment by gbaian10** [comment]
I think this is a bug, right?
Also, fixing this bug might cause some past commands to not output as expected, such as the changelog check.

**Comment by ljnsn** [comment]
[This](https://sw.kovidgoyal.net/kitty/faq/#some-special-symbols-are-rendered-small-truncated-in-kitty) is essentially the reason for the extra space. Without it those characters would get rendered small or truncated (in kitty) and they might overlap the next character on other symbols. Various other terminals/editors handle this differently, some always use the smaller symbol, some always overlap, etc.

In any case, I think it was wrong to add an extra space to those gitmojis to accommodate for the rendering in specific contexts, so we should remove it. The gitmoji is always followed by a space anyways, so it should render correctly. In some contexts it might "swallow" the space and the type will look like it's right next to the gitmoji, but I think that's acceptable.

> Also, fixing this bug might cause some past commands to not output as expected, such as the changelog check.

That is true, but we'll just make it a breaking change (even though it'll still only bump the minor version, since we're using `major_version_zero` until some of the main outstanding features have been implemented).
